# Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [15]:
import numpy as np
arr1=np.array([1,2,3,4,56,7])
print(arr1)
print(type(arr1))
print(arr1.shape)


[ 1  2  3  4 56  7]
<class 'numpy.ndarray'>
(6,)


In [18]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [19]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [20]:
arr2=np.array([[1,2,3,5,5,6],[9,8,7,6,5,4]])
print(arr2)
arr2.shape

[[1 2 3 5 5 6]
 [9 8 7 6 5 4]]


(2, 6)

In [26]:
import numpy as np
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

# inbuilt function in numpy
# np.ones()
# np.eye()


In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
# idnetity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [35]:
arr1=np.array([1,2,34,25])
arr2=np.array([10,25,34,54])

print("addition", arr1+arr2)
print("sub",arr1-arr2)

addition [11 27 68 79]
sub [ -9 -23   0 -29]


In [37]:
#universal function

#square root==np.sqrt()
#exponatinal==.exp()
#sine==.sin()
#log==.log()


arr1=np.array([2,3,4,5,6,7])

print(np.sqrt(arr))
print(np.sin(arr))
print(np.exp(arr))

[3.16227766 5.         5.83095189 7.34846923]
[-0.54402111 -0.13235175  0.52908269 -0.55878905]
[2.20264658e+04 7.20048993e+10 5.83461743e+14 2.83075330e+23]


In [50]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr[0][0]


np.int64(7)

In [53]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
arr[1][1]

np.int64(6)

In [55]:
arr[2][3]

np.int64(12)

In [56]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [58]:
##logical opertion 

data=np.array([1,2,3,4,5,6,7,8,9,7,8,9,5])
data[data>6]

array([7, 8, 9, 7, 8, 9])